import { IAuthor, ITheme } from "types";

export const authors = [
  { name: "Leonardo da Vinci", themes: [] },
  { name: "Vincent van Gogh", themes: [] },
  { name: "Claude Monet", themes: [] },
  { name: "Pablo Picasso", themes: [] },
  { name: "Michelangelo", themes: [] },
  { name: "Rembrandt", themes: [] },
  { name: "Salvador Dalí", themes: [] },
  { name: "Frida Kahlo", themes: [] },
] as IAuthor[];

export const themes = [
  {
    author: authors[0].name,
    backgroundColor: "#85DCB",
    primaryColor: "#E27D60",
    secondaryColor: "#C38D9E",
    textColor: "#fffff",
    title: "Colorful and Balanced",
  },
  {
    author: authors[0].name,
    backgroundColor: "#242582",
    primaryColor: "#F64C72",
    secondaryColor: "#553D67",
    textColor: "#fffff",
    title: "Bright Accent Colors",
  },
  {
    author: authors[1].name,
    backgroundColor: "#222831",
    primaryColor: "#00ADB5",
    secondaryColor: "#553D67",
    textColor: "#EEEEEE",
    title: `${authors[1].name}'s`,
  },
  {
    author: authors[2].name,
    backgroundColor: "#2D3047",
    primaryColor: "#0FA3B1",
    secondaryColor: "#B5E2FA",
    textColor: "#F9F7F3",
    title: `${authors[2].name}'s`,
  },
  {
    author: authors[3].name,
    backgroundColor: "#2D3047",
    primaryColor: "#ED217C",
    secondaryColor: "#1B998B",
    textColor: "#ffffff",
    title: `${authors[4].name}'s`,
  },
  {
    author: authors[4].name,
    backgroundColor: "#DBD4D3",
    primaryColor: "#387780",
    secondaryColor: "#D2CCA1",
    textColor: "#111111",
    title: `${authors[4].name}'s v2`,
  },
  {
    author: authors[5].name,
    backgroundColor: "#0A210F",
    primaryColor: "#F7A9A8",
    secondaryColor: "#BFD2BF",
    textColor: "#ffffff",
    title: `${authors[5].name}'s`,
  },
  {
    author: authors[6].name,
    backgroundColor: "#0A210F",
    primaryColor: "#4A2545",
    secondaryColor: "#AEF6C7",
    textColor: "#eeeeee",
    title: `${authors[6].name}'s`,
  },
  {
    author: authors[7].name,
    backgroundColor: "#080705",
    primaryColor: "#912F40",
    secondaryColor: "#AEF6C7",
    textColor: "#ffffff",
    title: `${authors[7].name}'s`,
  },
  {
    author: authors[7].name,
    backgroundColor: "#0D0628",
    primaryColor: "#A1BA89",
    secondaryColor: "#F5DDDD",
    textColor: "#F1F2EB",
    title: `${authors[7].name}'s v2`,
  },
] as ITheme[];
